version: '3'
services:
  mysql:
    container_name: some-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
      SE_OPTS: "log log.txt"
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql
    logging:
      driver: none
  prestashop:
    container_name: prestashop
    image: prestashop-custom:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
      - 8443:443
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_FOLDER_ADMIN: admin4577
      PS_FOLDER_INSTALL: install4577
      PS_ENABLE_SSL: 1
      PS_SHOP_DOMAIN: http://localhost:8080/
      PS_SHOP_DOMAIN_SSL: https://localhost:8443/
    networks:
      - prestashop_network
    volumes:
      - psdata:/var/www/html
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: some-mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      SE_OPTS: "log log.txt"
    restart: unless-stopped
    ports:
      - 8081:80
    networks:
      - prestashop_network
    logging:
      driver: none
networks:
  prestashop_network:
volumes:
  psdata:
  dbdata: